#!/bin/bash
# copy data
sh /home/user/my-stuffs/apache-tomcat-7.0.39/bin/catalina.sh stop
echo "Server stopped!"
mvn clean compile install -Dmaven.test.skip=true
echo "Code compiled!"
rm -fr /home/user/my-stuffs/apache-tomcat-7.0.39/webapps/office-cube
echo "Folder removed!"
cp /home/user/O3/target/office-cube.war /home/user/my-stuffs/apache-tomcat-7.0.39/webapps
echo "File copied!"
sh /home/user/my-stuffs/apache-tomcat-7.0.39/bin/catalina.sh jpda start
echo "Application Ready!"